rootPageId: 1
base: /
baseVariants: {  }
languages:
  -
    title: English
    enabled: true
    languageId: '0'
    base: /
    typo3Language: default
    locale: en_US.UTF-8
    iso-639-1: en
    navigationTitle: English
    hreflang: en-US
    direction: ltr
    flag: us
  -
    title: Svenska
    enabled: true
    languageId: '1'
    base: /sv/
    typo3Language: sv
    locale: sv_SE.UTF-8
    iso-639-1: sv
    navigationTitle: Svenska
    hreflang: sv-SE
    direction: ltr
    fallbackType: strict
    flag: se
  -
    title: Deutsch
    enabled: true
    languageId: '2'
    base: /de/
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle: Deutsch
    hreflang: de-DE
    direction: ltr
    fallbackType: strict
    flag: de
errorHandling:
  -
    errorCode: '404'
    errorHandler: Page
    errorContentSource: 't3://page?uid=78'
routes:
  -
    route: robots.txt
    type: staticText
    content: "User-agent: *\r\nDisallow: /typo3/\r\nDisallow: /typo3_src/\r\nAllow: /typo3/sysext/frontend/Resources/Public/*"
