version: "3.1"

services:

  t3kit_db:
    container_name: ${DB_CONTAINER_NAME}
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./docker_conf/mysqlconf:/etc/mysql/mysql.conf.d${CACHED}

  web:
    container_name: ${WEB_CONTAINER_NAME}
    image: ${WEB_IMAGE}
    ports:
      - "${WEB_PORT}:80"
    depends_on:
      - t3kit_db
      - t3kit_solr
    volumes:
      - ./docker_conf:/docker_conf${CACHED}
      - .:/var/www/html${CACHED}
      - /var/www/html/web/typo3temp
    environment:
      - USERID=${WEB_USERID}
      - GROUPID=${WEB_GROUPID}

      - WEB_CONTAINER_NAME=${WEB_CONTAINER_NAME}
      - SOLR_CONTAINER_NAME=${SOLR_CONTAINER_NAME}
      - MAILHOG_CONTAINER_NAME=${MAILHOG_CONTAINER_NAME}

      - DB_CONTAINER_NAME=${DB_CONTAINER_NAME}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}

    command: "sh /docker_conf/run.sh"

  t3kit_solr:
    container_name: ${SOLR_CONTAINER_NAME}
    image: typo3solr/ext-solr:9.0.0
    ports:
      - "${SOLR_PORT}:8983"
    volumes:
      - ./solrdata:/opt/solr/server/solr/data${CACHED}

  mailhog:
    container_name: ${MAILHOG_CONTAINER_NAME}
    image: mailhog/mailhog
    ports:
      - "${MAILHOG_PORT}:8025"
