version: 2
jobs:
  build:
    working_directory: /var/www/html
    docker:
      - image: t3kit/ubuntu16-php7-apache:0.0.1
        environment:
          APP_ENV: local
          APP_DEBUG: true
          APP_KEY: kjcndjjksddwdwdw
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: t3kit
          DB_USERNAME: t3kit
          DB_PASSWORD: t3kit1234
      - image: mariadb:5.5
        environment:
          MYSQL_ROOT_PASSWORD: 1234
          MYSQL_DATABASE: t3kit
          MYSQL_USER: t3kit
          MYSQL_PASSWORD: t3kit1234
    steps:
      - checkout
      - setup_docker_engine
      - run:
          name: Install Composer
          command: |
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
            php -r "copy('https://composer.github.io/installer.sig', 'composer-setup.sig');" && \
            php -r "if (hash_file('SHA384', 'composer-setup.php') === trim(file_get_contents('composer-setup.sig'))) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" && \
            php composer-setup.php && \
            php -r "unlink('composer-setup.php');"
      - run:
          name: Install Project Dependencies
          command: php composer.phar install
      #- run:
      #    name: Install Docker client
      #    command: |
      #      set -x
      #      VER="17.03.0-ce"
      #      curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
      #      tar -xz -C /tmp -f /tmp/docker-$VER.tgz
      #      mv /tmp/docker/* /usr/bin
      #- run:
      #    name: Install t3kit database
      #    command: |
      #      docker ps
      - run:
          name: Install t3kit database
          command: |
            docker exec -it $DOCKER_MACHINE_NAME vendor/t3kit/db/setupdb.sh